const express=require("express"),multer=require("multer"),path=require("path"),fs=require("fs/promises"),crypto=require("crypto"),sharp=require("sharp");const{PDFDocument}=require("pdf-lib");
const app=express(),PORT=process.env.PORT||5000,MAX=Number(process.env.MAX_UPLOAD_BYTES||1073741824),BASE=path.join(__dirname,"storage"),UP=path.join(BASE,"uploads"),OUT=path.join(BASE,"outputs");
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,UP),filename:(_r,f,cb)=>cb(null,crypto.randomUUID()+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:MAX,files:1},fileFilter:(_r,f,cb)=>cb(null,["image/jpeg","image/png","application/pdf"].includes(f.mimetype))});
const kb=n=>Math.round(n/1024*100)/100;
async function magic(p,type){const h=await fs.open(p,"r");try{const b=Buffer.alloc(12);const x=await h.read(b,0,12,0),q=b.subarray(0,x.bytesRead);if(type==="application/pdf")return q.subarray(0,5).toString()==="%PDF-";if(type==="image/jpeg")return q[0]===255&&q[1]===216&&q[2]===255;if(type==="image/png")return q.equals(Buffer.from([137,80,78,71,13,10,26,10]));return false}finally{await h.close()}}
async function image(infile,outfile,o){const meta=await sharp(infile,{limitInputPixels:268402689}).rotate().metadata();let w=o.width,h=o.height,q=Math.min(95,Math.max(20,o.quality||82)),best=null,fmt=["jpg","png","webp"].includes(o.format)?o.format:"jpg";
for(let i=0;i<12;i++){let p=sharp(infile,{limitInputPixels:268402689}).rotate();if(w||h)p=p.resize({width:w,height:h,fit:"inside",withoutEnlargement:true,fastShrinkOnLoad:true});if(fmt==="jpg")p=p.jpeg({quality:q,mozjpeg:true,progressive:true});if(fmt==="webp")p=p.webp({quality:q});if(fmt==="png")p=p.png({compressionLevel:9,palette:true});const buf=await p.toBuffer(),size=kb(buf.length);if(!best||Math.abs(size-(o.target||size))<Math.abs(best.size-(o.target||size)))best={buf,size,q};if(!o.target||size<=o.target)break;if(fmt!=="png"&&q>30)q-=7;else{w=w?Math.max(64,Math.floor(w*.88)):Math.max(64,Math.floor((meta.width||800)*.88));h=h?Math.max(64,Math.floor(h*.88)):Math.max(64,Math.floor((meta.height||800)*.88))}}
if(o.target&&best.size>o.target&&fmt==="png"){const b=await sharp(infile,{limitInputPixels:268402689}).rotate().resize({width:w,height:h,fit:"inside",withoutEnlargement:true}).jpeg({quality:70,mozjpeg:true,progressive:true}).toBuffer();if(b.length<best.buf.length)best={buf:b,size:kb(b.length),q:70,actual:"jpg"}}
await fs.writeFile(outfile,best.buf);return{originalWidth:meta.width||null,originalHeight:meta.height||null,finalSizeKB:best.size,requestedTargetKB:o.target||null,finalQuality:best.q,format:best.actual||fmt,targetMet:o.target?best.size<=o.target:true}}
async function pdf(infile,outfile,target){const src=await fs.readFile(infile),doc=await PDFDocument.load(src),buf=await doc.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:50});await fs.writeFile(outfile,buf);const s=kb(buf.length);return{finalSizeKB:s,requestedTargetKB:target||null,targetMet:target?s<=target:s<=kb(src.length),note:"PDF structural optimization applied. Deep recompression of embedded scans/images may require a dedicated PDF engine."}}
app.get("/api/health",(_r,s)=>s.json({ok:true,maxUploadMB:Math.round(MAX/1048576)}));
app.post("/api/optimize",upload.single("file"),async(req,res)=>{let inp=req.file?.path,out=null;try{if(!req.file)return res.status(400).json({error:"Please upload JPG, PNG or PDF."});if(!(await magic(inp,req.file.mimetype)))return res.status(400).json({error:"File content does not match its declared type."});const target=Number(req.body.targetKB)>0?Number(req.body.targetKB):null,w=Number(req.body.width)>0?Number(req.body.width):null,h=Number(req.body.height)>0?Number(req.body.height):null,q=Number(req.body.quality)>0?Number(req.body.quality):82,fmt=String(req.body.format||"jpg").toLowerCase(),st=await fs.stat(inp);let result,ext;if(req.file.mimetype==="application/pdf"){ext=".pdf";out=path.join(OUT,crypto.randomUUID()+ext);result=await pdf(inp,out,target)}else{fmt=["jpg","png","webp"].includes(fmt)?fmt:"jpg";ext="."+fmt;out=path.join(OUT,crypto.randomUUID()+ext);result=await image(inp,out,{target,width:w,height:h,quality:q,format:fmt})}const ost=await fs.stat(out),orig=kb(st.size),fin=kb(ost.size);res.json({success:true,file:{originalName:req.file.originalname,originalKB:orig,finalKB:fin,savedKB:Math.max(0,Math.round((orig-fin)*100)/100),downloadUrl:"/api/download/"+path.basename(out)},result})}catch(e){console.error(e);if(out)await fs.rm(out,{force:true}).catch(()=>{});res.status(500).json({error:"Processing failed. The file may be invalid, too complex, or the server may be under resource pressure."})}finally{if(inp)await fs.rm(inp,{force:true}).catch(()=>{})}});
app.get("/api/download/:name",async(req,res)=>{const name=path.basename(req.params.name);if(name!==req.params.name)return res.status(400).json({error:"Invalid file name."});const p=path.join(OUT,name);try{await fs.access(p);res.download(p,name,async()=>await fs.rm(p,{force:true}).catch(()=>{}))}catch{res.status(404).json({error:"File not found or already removed."})}});
(async()=>{await fs.mkdir(UP,{recursive:true});await fs.mkdir(OUT,{recursive:true});app.listen(PORT,()=>console.log("SmartFile 2.0: http://localhost:"+PORT))})();
